### PR TITLE
Release 0.1.0 (PR 2)

### PR DESCRIPTION
**Pull request by ninjabear**
Previous pull request: #1

### CODE REVIEW

**Comment by ninjabear** [comment]
# What's changed
1. Readme is now as Scala tracker (4 boxes, Technical, Set-up, Roadmap, Contributing)
2. Package name is now `com.snowplowanalytics.sources.awslambda`
3. Javadoc is written
4. The install script has been rewritten in Python
   - You'll need to `pip install pyyaml`
   - The configuration is expected in config.yaml
   - The automated release process **now creates two artifacts**. One is the bundle containing all files, including `deploy.py` required to deploy the lambda (`snowplow_aws_lambda_0.1.0-rc1_bundle.zip`). The other sans `bundle` is _just the AWS lambda zip file_.
5. Vagrant / push.bash will work as before (though I don't anticipate it'll be used)
6. The bundle version is built dynamically - to change versions you just need to edit the `version` declaration in `build.gradle`
7.  The _using the web interface_ section from the set-up guide has been removed
8. Information about redshift tables has been added to the documentation

**Comment by ninjabear** [comment]
Hey @alexanderdean, can you take another look at this please! I've also updated the blog post https://github.com/snowplow/snowplow.github.com/pull/311

**Comment by alexanderdean** [comment]
Hey @ninjabear - a quick piece of feedback (sorry for the delay). I will struggle to put this live without the ability to specify an `app_id`. All of the event streams that feed into Snowplow's unified log have an app ID.

This is what the Snowplow tracking configuration section looks like for EmrEtlRunner:

``` yaml
  snowplow: 
    method: get
    app_id: managed-service
    collector: collector-foo.acme.com
```

I'm okay for us not to specify the `method` (but create a ticket to make that configurable in the 0.2.0, and we need to specify which `method` we are using in the documentation). But we need to make the `app_id` configurable for sure...

**Comment by alexanderdean** [comment]
Closing this - please re-open once the app_id (and possible method) are configurable...

**Pull request closed without merging**
